<?php

namespace ContainerLoVRqte;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HbKz5OZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hbKz5OZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hbKz5OZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'EvenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'mr' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'EvenementRepository' => 'App\\Repository\\EvenementRepository',
            'mr' => '?',
        ]);
    }
}
