<?php

namespace ContainerLoVRqte;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BNnynwZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bNnynwZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bNnynwZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ParticipationRepository' => ['privates', 'App\\Repository\\ParticipationRepository', 'getParticipationRepositoryService', true],
        ], [
            'ParticipationRepository' => 'App\\Repository\\ParticipationRepository',
        ]);
    }
}
