<?php

namespace ContainerLoVRqte;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RnAugYPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rnAugYP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rnAugYP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EvenementController::add' => ['privates', '.service_locator.U4v.QS5', 'get_ServiceLocator_U4v_QS5Service', true],
            'App\\Controller\\EvenementController::delete' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.u4bBF5Z', 'get_ServiceLocator_U4bBF5ZService', true],
            'App\\Controller\\EvenementController::indexFront' => ['privates', '.service_locator.lMu38_I', 'get_ServiceLocator_LMu38IService', true],
            'App\\Controller\\EvenementController::indexFrontRate' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Controller\\EvenementController::update' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Controller\\ParticipationController::add' => ['privates', '.service_locator.v_7Kktc', 'get_ServiceLocator_V7KktcService', true],
            'App\\Controller\\ParticipationController::delete' => ['privates', '.service_locator.uJce8t4', 'get_ServiceLocator_UJce8t4Service', true],
            'App\\Controller\\ParticipationController::index' => ['privates', '.service_locator.bNnynwZ', 'get_ServiceLocator_BNnynwZService', true],
            'App\\Controller\\ParticipationController::sendSMS' => ['privates', '.service_locator.u4bBF5Z', 'get_ServiceLocator_U4bBF5ZService', true],
            'App\\Controller\\ParticipationController::update' => ['privates', '.service_locator.uJce8t4', 'get_ServiceLocator_UJce8t4Service', true],
            'App\\Controller\\RatingSystemController::add' => ['privates', '.service_locator.U4v.QS5', 'get_ServiceLocator_U4v_QS5Service', true],
            'App\\Controller\\RatingSystemController::delete' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Controller\\RatingSystemController::index' => ['privates', '.service_locator.u4bBF5Z', 'get_ServiceLocator_U4bBF5ZService', true],
            'App\\Controller\\RatingSystemController::update' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\EvenementController:add' => ['privates', '.service_locator.U4v.QS5', 'get_ServiceLocator_U4v_QS5Service', true],
            'App\\Controller\\EvenementController:delete' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.u4bBF5Z', 'get_ServiceLocator_U4bBF5ZService', true],
            'App\\Controller\\EvenementController:indexFront' => ['privates', '.service_locator.lMu38_I', 'get_ServiceLocator_LMu38IService', true],
            'App\\Controller\\EvenementController:indexFrontRate' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Controller\\EvenementController:update' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Controller\\ParticipationController:add' => ['privates', '.service_locator.v_7Kktc', 'get_ServiceLocator_V7KktcService', true],
            'App\\Controller\\ParticipationController:delete' => ['privates', '.service_locator.uJce8t4', 'get_ServiceLocator_UJce8t4Service', true],
            'App\\Controller\\ParticipationController:index' => ['privates', '.service_locator.bNnynwZ', 'get_ServiceLocator_BNnynwZService', true],
            'App\\Controller\\ParticipationController:sendSMS' => ['privates', '.service_locator.u4bBF5Z', 'get_ServiceLocator_U4bBF5ZService', true],
            'App\\Controller\\ParticipationController:update' => ['privates', '.service_locator.uJce8t4', 'get_ServiceLocator_UJce8t4Service', true],
            'App\\Controller\\RatingSystemController:add' => ['privates', '.service_locator.U4v.QS5', 'get_ServiceLocator_U4v_QS5Service', true],
            'App\\Controller\\RatingSystemController:delete' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'App\\Controller\\RatingSystemController:index' => ['privates', '.service_locator.u4bBF5Z', 'get_ServiceLocator_U4bBF5ZService', true],
            'App\\Controller\\RatingSystemController:update' => ['privates', '.service_locator.hbKz5OZ', 'get_ServiceLocator_HbKz5OZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\EvenementController::add' => '?',
            'App\\Controller\\EvenementController::delete' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::indexFront' => '?',
            'App\\Controller\\EvenementController::indexFrontRate' => '?',
            'App\\Controller\\EvenementController::update' => '?',
            'App\\Controller\\ParticipationController::add' => '?',
            'App\\Controller\\ParticipationController::delete' => '?',
            'App\\Controller\\ParticipationController::index' => '?',
            'App\\Controller\\ParticipationController::sendSMS' => '?',
            'App\\Controller\\ParticipationController::update' => '?',
            'App\\Controller\\RatingSystemController::add' => '?',
            'App\\Controller\\RatingSystemController::delete' => '?',
            'App\\Controller\\RatingSystemController::index' => '?',
            'App\\Controller\\RatingSystemController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EvenementController:add' => '?',
            'App\\Controller\\EvenementController:delete' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:indexFront' => '?',
            'App\\Controller\\EvenementController:indexFrontRate' => '?',
            'App\\Controller\\EvenementController:update' => '?',
            'App\\Controller\\ParticipationController:add' => '?',
            'App\\Controller\\ParticipationController:delete' => '?',
            'App\\Controller\\ParticipationController:index' => '?',
            'App\\Controller\\ParticipationController:sendSMS' => '?',
            'App\\Controller\\ParticipationController:update' => '?',
            'App\\Controller\\RatingSystemController:add' => '?',
            'App\\Controller\\RatingSystemController:delete' => '?',
            'App\\Controller\\RatingSystemController:index' => '?',
            'App\\Controller\\RatingSystemController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
