<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPAMnw5C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPAMnw5C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPAMnw5C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPAMnw5C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPAMnw5C\App_KernelDevDebugContainer([
    'container.build_hash' => 'PAMnw5C',
    'container.build_id' => '3e00e13c',
    'container.build_time' => 1714594491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPAMnw5C');
