<?php

namespace ContainerPAMnw5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U4bBF5ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u4bBF5Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u4bBF5Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'EvenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'EvenementRepository' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
